services:

  postgres:
    image: postgres:15
    container_name: hms_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: healthcare_db
      POSTGRES_USER: healthcare_user
      POSTGRES_PASSWORD: healthcare_pass
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  django:
    build:
      context: ./healthcare
      dockerfile: Dockerfile
    container_name: hms_django
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./healthcare:/app
    ports:
      - "8000:8000"
    env_file:
      - ./healthcare/.env
    depends_on:
      - postgres

volumes:
  postgres_data:

